In [10]:
import pandas as pd

In [11]:
url = "steam_db_top_1000.html"

In [12]:
tables = pd.read_html(url)
tables

[        #  Unnamed: 1                            Name  Positive  Negative  \
 0     1.0         NaN                 Team Fortress 2    658679     41741
 1     2.0         NaN                     Garry's Mod    579296     21624
 2     3.0         NaN                        Terraria    573328     12729
 3     4.0         NaN        The Witcher 3: Wild Hunt    403369      7932
 4     5.0         NaN                   Left 4 Dead 2    372527     10969
 ..    ...         ...                             ...       ...       ...
 95   96.0         NaN                       Duck Game     24279       940
 96   97.0         NaN                         Celeste     24031       556
 97   98.0         NaN                    Titanfall® 2     23815      1077
 98   99.0         NaN               The Wolf Among Us     23556       572
 99  100.0         NaN  The Elder Scrolls IV: Oblivion     23147      1118

     Rating Positive.1
 0   93.27%     94.04%
 1   95.56%     96.40%
 2   96.95%     97.83%
 3   97.09%     98.07%
 4   96.16%     97.14%
 ..     ...        ...
 95  94.08%     96.27%
 96  95.46%     97.74%
 97  93.50%     95.67%
 98  95.35%     97.63%
 99  93.22%     95.39%

 [100 rows x 7 columns]]

In [16]:
steam_df = tables[0]
steam_df = steam_df.drop("Unnamed: 1", axis=1)
steam_df

,#,Name,Positive,Negative,Rating,Positive.1
0,1.0,Team Fortress 2,658679,41741,93.27%,94.04%
1,2.0,Garry's Mod,579296,21624,95.56%,96.40%
2,3.0,Terraria,573328,12729,96.95%,97.83%
3,4.0,The Witcher 3: Wild Hunt,403369,7932,97.09%,98.07%
4,5.0,Left 4 Dead 2,372527,10969,96.16%,97.14%
...,...,...,...,...,...,...
95,96.0,Duck Game,24279,940,94.08%,96.27%
96,97.0,Celeste,24031,556,95.46%,97.74%
97,98.0,Titanfall® 2,23815,1077,93.50%,95.67%
98,99.0,The Wolf Among Us,23556,572,95.35%,97.63%
99,100.0,The Elder Scrolls IV: Oblivion,23147,1118,93.22%,95.39%